tables:
  page_counter_v2_page:
    field:
      session_id:
        type: varchar(255)
      HTTP_HOST:
        type: mediumtext
      HTTP_USER_AGENT:
        type: mediumtext
      HTTP_REFERER:
        type: mediumtext
      HTTP_COOKIE:
        type: mediumtext
      REMOTE_ADDR:
        type: mediumtext
      REQUEST_URI:
        type: mediumtext
      theme:
        type: varchar(255)
      class:
        type: varchar(255)
      method:
        type: varchar(255)
      language:
        type: varchar(255)
      REQUEST_METHOD:
        type: varchar(255)
      post_data:
        type: mediumtext
extra:
  _description: Extra field to add to each table if not exist in schema.
  field:
    created_at:
      type: timestamp
      default: CURRENT_TIMESTAMP
    updated_at:
      type: timestamp
    created_by:
      type: varchar(50)
    updated_by:
      type: varchar(50)    
